from dotenv import load_dotenv
import os

load_dotenv()

NEW_JSON_TOKENIZER_PATH = os.getenv("NEW_JSON_TOKENIZER_PATH")
TXT_DATASET_PATH = os.getenv("TXT_DATASET_PATH")
JSON_TOKENIZER_PATH = os.getenv("JSON_TOKENIZER_PATH")
WORD2VEC_MODEL_PATH = os.getenv("WORD2VEC_MODEL_PATH")
TOKENIZER_DATASET_TEXT_LIMIT = int(os.getenv("TOKENIZER_DATASET_TEXT_LIMIT"))
VECTOR_DIMENTIONS = int(os.getenv("VECTOR_DIMENTIONS"))
EMBEDDING_PATH = os.getenv("EMBEDDING_PATH")
VAM_PATH = os.getenv("VAM_PATH")
PUSHOVER_TOKEN = os.getenv("PUSHOVER_TOKEN")
PUSHOVER_USER_KEY = os.getenv("PUSHOVER_USER_KEY")